import type { Metadata } from "next"
import { Inter } from "next/font/google"
import { ReactNode } from "react"
import { StoreProvider } from "../app/storeProvider"
import { Nav } from "../app/components/nav/nav"

import "./globals.css"

const inter = Inter({ subsets: ["latin"] })

interface Props {
  readonly children: ReactNode
}

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({ children }: Props) {
  return (
    <StoreProvider>
      <html lang="en">
        <body>
          <div>Hello Bob</div>
          <p>It's working, IT'S WORKING!!!!!</p>
          <Nav />
        </body>
      </html>
    </StoreProvider>
  )
}
